In [1]:
import seaborn as sns
df = sns.load_dataset('titanic')
import numpy as np
import pandas as pd

In [2]:
DF = df.to_csv('titanic.csv', index = False)

In [3]:
df.sample(4)

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
853         1       1  female  16.0      0      1  39.4000        S   First   
576         1       2  female  34.0      0      0  13.0000        S  Second   
551         0       2    male  27.0      0      0  26.0000        S  Second   
315         1       3  female  26.0      0      0   7.8542        S   Third   

       who  adult_male deck  embark_town alive  alone  
853  woman       False    D  Southampton   yes  False  
576  woman       False  NaN  Southampton   yes   True  
551    man        True  NaN  Southampton    no   True  
315  woman       False  NaN  Southampton   yes   True

In [4]:
#getting most important features

df = df[['sex','embarked','alone','pclass','survived']]
df.head()

sex embarked  alone  pclass  survived
0    male        S  False       3         0
1  female        C  False       1         1
2  female        S   True       3         1
3  female        S  False       1         1
4    male        S   True       3         0

In [5]:
#Changing string value in to 0 and 1

df['sex'] = np.where(df['sex']=="male",1,0)
df.head()

sex embarked  alone  pclass  survived
0    1        S  False       3         0
1    0        C  False       1         1
2    0        S   True       3         1
3    0        S  False       1         1
4    1        S   True       3         0

In [6]:
#lets perform on embarked

import numpy as np
ordinal_label = {k: i for i,k in enumerate(df['embarked'].unique(),0)}
df['embarked'] = df['embarked'].map(ordinal_label)

In [7]:
df.sample(10)

sex  embarked  alone  pclass  survived
63     1         0  False       3         0
890    1         2   True       3         0
98     0         0  False       2         1
143    1         2   True       3         0
299    0         1  False       1         1
600    0         0  False       2         1
887    0         0   True       1         1
778    1         2   True       3         0
725    1         0   True       3         0
886    1         0   True       2         0

In [8]:
df['alone'] = np.where(df['alone']==True,1,0)

In [9]:
df.head()

sex  embarked  alone  pclass  survived
0    1         0      0       3         0
1    0         1      0       1         1
2    0         0      1       3         1
3    0         0      0       1         1
4    1         0      1       3         0

In [10]:
from sklearn.model_selection import train_test_split
X = df[['sex','embarked','alone','pclass']]
y = df['survived']

X_train,X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=100)


In [11]:
X_train.head()

sex  embarked  alone  pclass
69     1         0      0       3
85     0         0      0       3
794    1         0      1       3
161    0         0      1       2
815    1         0      1       1

In [12]:
X_train['sex'].unique()

array([1, 0])

In [13]:
X_train.isnull().sum()

sex         0
embarked    0
alone       0
pclass      0
dtype: int64

In [14]:

#Perform chi2 test
#chi2 returns 2 values
#Fscore and the pvalue

from sklearn.feature_selection import chi2
f_p_values = chi2(X_train,y_train)

In [15]:
f_p_values

(array([65.67929505,  7.55053653, 10.88471585, 21.97994154]),
 array([5.30603805e-16, 5.99922095e-03, 9.69610546e-04, 2.75514881e-06]))

In [16]:
import pandas as pd
p_values = pd.Series(f_p_values)
p_values.index

RangeIndex(start=0, stop=2, step=1)