In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statistics
import statsmodels
from sklearn import datasets
wine = datasets.load_wine()
wine.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [2]:
wine.target_names
wine.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [3]:
dt = wine.data
X = pd.DataFrame(dt,columns=wine.feature_names)
X.sample(5)

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
16     14.30        1.92  2.72               20.0      120.0           2.80   
72     13.49        1.66  2.24               24.0       87.0           1.88   
126    12.43        1.53  2.29               21.5       86.0           2.74   
44     13.05        1.77  2.10               17.0      107.0           3.00   
95     12.47        1.52  2.20               19.0      162.0           2.50   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
16         3.14                  0.33             1.97             6.20  1.07   
72         1.84                  0.27             1.03             3.74  0.98   
126        3.15                  0.39             1.77             3.94  0.69   
44         3.00                  0.28             2.03             5.04  0.88   
95         2.27                  0.32             3.28             2.60  1.16   

     od280/od315_of_diluted_wines  proline  
16                           2.65   1280.0  
72                           2.78    472.0  
126                          2.84    352.0  
44                           3.35    885.0  
95                           2.63    937.0

In [4]:
y = pd.DataFrame(wine.target,columns=['TARGET'])
y.sample(5)

TARGET
168       2
107       1
11        0
101       1
129       1

In [5]:
# #Standradization

# from sklearn.preprocessing import StandardScaler

# scaler = StandardScaler()

# scaler.fit(X)

In [6]:
# scaler_feature = scaler.transform(X)

# df_feature = pd.DataFrame(scaler_feature,columns=wine.feature_names)

In [7]:
# X = df_feature
# X.head()

In [8]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=10)

In [9]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5);
knn.fit(X_train,y_train)

c:\python39\lib\site-packages\sklearn\neighbors\_classification.py:200: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [10]:
pred = knn.predict(X_test)

In [11]:
pred

array([2, 1, 0, 1, 0, 1, 1, 2, 2, 0, 0, 1, 0, 1, 1, 2, 2, 2, 2, 2, 0, 2,
       0, 0, 1, 2, 2, 2, 2, 1, 1, 2, 0, 2, 1, 0, 0, 1, 2, 1, 1, 2, 0, 1,
       0, 1, 2, 2, 2, 2, 2, 2, 1, 0])

In [12]:
from sklearn.metrics import classification_report , confusion_matrix

print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))

[[11  0  4]
 [ 2 15 10]
 [ 1  2  9]]
              precision    recall  f1-score   support

           0       0.79      0.73      0.76        15
           1       0.88      0.56      0.68        27
           2       0.39      0.75      0.51        12

    accuracy                           0.65        54
   macro avg       0.69      0.68      0.65        54
weighted avg       0.75      0.65      0.67        54



In [15]:
def findClass():
    val = knn.predict([[14.23,1.71,2.43,15.6,127,2.8,3.06,0.28,2.29,5.64,1.04,3.92,1065]])
    if(val==0):
        return "Class - 0"
    if(val==1):
        return "Class - 1"
    if(val==2):
        return "Class - 2"

In [16]:
findClass()

c:\python39\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


'Class - 0'