In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statistics
import statsmodels

In [2]:
#Loading Data

df = sns.load_dataset('iris')
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
df.species

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [4]:
def replace_target(x):
    if x=='setosa':
        return 0
    elif x=='versicolor':
        return 1
    else:
        return 2
    

In [5]:
df['species'] = df['species'].apply(replace_target)

In [6]:
df.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [7]:
df.sample(10)

sepal_length  sepal_width  petal_length  petal_width  species
96            5.7          2.9           4.2          1.3        1
16            5.4          3.9           1.3          0.4        0
58            6.6          2.9           4.6          1.3        1
40            5.0          3.5           1.3          0.3        0
103           6.3          2.9           5.6          1.8        2
9             4.9          3.1           1.5          0.1        0
109           7.2          3.6           6.1          2.5        2
79            5.7          2.6           3.5          1.0        1
86            6.7          3.1           4.7          1.5        1
19            5.1          3.8           1.5          0.3        0

In [8]:
X = df.drop(labels=['species'],axis=1)
y = df['species']

In [9]:
#Spliting

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)

In [10]:
#KNN

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()

knn.fit(X_train,y_train)

KNeighborsClassifier()

In [11]:
#Prediction

pred = knn.predict(X_test)

In [12]:
#Prediction and Evaluation
from sklearn.metrics import confusion_matrix , classification_report

print(confusion_matrix(y_test,pred))

[[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]


In [13]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.94      0.97        18
           2       0.92      1.00      0.96        11

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45



In [14]:
X_test.head()

sepal_length  sepal_width  petal_length  petal_width
114           5.8          2.8           5.1          2.4
62            6.0          2.2           4.0          1.0
33            5.5          4.2           1.4          0.2
107           7.3          2.9           6.3          1.8
7             5.0          3.4           1.5          0.2

In [15]:
def pred_species():
    a = float(input("Enter Sepal_Length : "))
    b = float(input("Enter Sepal_Width : "))
    c = float(input("Enter Petal_Length : "))
    d = float(input("Enter Petal_Width : "))
    val = knn.predict([[a,b,c,d]])
    if(val==0):
        return 'setosa'
    if(val==1):
        return 'versicolor'
    else:
        return 'virginica'

In [16]:
pred_species()

Enter Sepal_Length : 2.1
Enter Sepal_Width : 2.33
Enter Petal_Length : 2.1
Enter Petal_Width : 2.6


c:\python39\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


'setosa'

In [17]:
from sklearn.metrics import accuracy_score

accuracy_score(pred,y_test)*100

97.77777777777777

In [6]:
import calendar

print(calendar.month(theyear=2040,themonth=11))

   November 2040
Mo Tu We Th Fr Sa Su
          1  2  3  4
 5  6  7  8  9 10 11
12 13 14 15 16 17 18
19 20 21 22 23 24 25
26 27 28 29 30



In [7]:
from datetime import datetime

# get current datetime
dt = datetime.now()
print('Datetime is:', dt)
print('Weekday is:', dt.isoweekday())

Datetime is: 2022-11-18 11:30:49.409180
Weekday is: 5
