In [1]:
#SKLEARN
import sklearn
print('Sklearn version =',sklearn.__version__)

Sklearn version = 1.1.1


In [4]:
from sklearn.datasets import load_iris
iris = load_iris()
print(iris.data)
iris.feature_names #finding features

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [7]:
iris.target#finding the targets of iris dataset

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
iris.target_names#names of target outputs

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [22]:
feature_matrix = iris.data
feature_names = iris.feature_names
target_matrix = iris.target
feature_matrix[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [27]:
import pandas as pd
import numpy as np
import statistics
import statsmodels
import seaborn as sns
import matplotlib.pyplot as plt

In [31]:
df = pd.DataFrame(feature_matrix,columns=feature_names)
df
#add target column to df
df['species (target)'] = target_matrix
df.sample(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
42                4.4               3.2                1.3               0.2   
68                6.2               2.2                4.5               1.5   
12                4.8               3.0                1.4               0.1   
78                6.0               2.9                4.5               1.5   
29                4.7               3.2                1.6               0.2   

    species (target)  
42                 0  
68                 1  
12                 0  
78                 1  
29                 0

In [32]:
#changing target value 
def replace_target(x):
    if x==0:
        return 'setosa'
    elif x==1:
        return 'versicolor'
    else:
        return 'virginica'

#Now call the function

df['species-names'] = df['species (target)'].apply(replace_target)

In [34]:
df.sample()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
60                5.0               2.0                3.5               1.0   

    species (target) species-names  
60                 1    versicolor

In [40]:
#TRAIN AND TEST spliting
from sklearn.model_selection import train_test_split
#X_train, X_test, y_train, y_test = train_test_split(feature_matrix, target_matrix, train/test_size, random_state)

X_train, X_test, y_train, y_test = train_test_split(feature_matrix, target_matrix, train_size = 0.6, random_state=101)
X_train.shape, X_test.shape

((90, 4), (60, 4))

In [ ]:
#Linear Regression 